const CHANGE_FUEL_TYPE = "CHANGE_FUEL_TYPE";
const CLEAR_FILTER = "CLEAR_FILTER";
const CHANGE_BUDGET = "CHANGE_BUDGET"
const CHANGE_SORT_BY = "CHANGE_SORT_BY";
const CHANGE_MAKE_ID = "CHANGE_MAKE_ID";
const CHANGE_CITY = "CHANGE_CITY";


export { CHANGE_FUEL_TYPE, CLEAR_FILTER, CHANGE_BUDGET, CHANGE_SORT_BY, CHANGE_MAKE_ID, CHANGE_CITY }